import type { Metadata } from 'next'
import Link from 'next/link'
import { Lato, Inter } from 'next/font/google'
import './globals.css'

const lato = Lato({ weight: ['300', '700'], subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={lato.className}>
        <header className='p4 bg-gray-100'>
          <nav className='container py-4'>
            <ul className='flex gap-3'>
              <li>
                <Link href='/'>Home</Link>
              </li>
              <li>
                <Link href='/about'>About</Link>
              </li>
              <li>
                <Link href='/guestbook'>Guest Book</Link>
              </li>
            </ul>
          </nav>
        </header>
        <main>{children}</main>
      </body>
    </html>
  )
}
